---
title: "Forecasting Air Quality Index in London"
author: "Anusha Bhat, Sarah Chaker, Hritik Jhaveri, John Melel"
date: "2025-03-13"
output:
  pdf_document:
    latex_engine: xelatex
linestretch: 1.241
fontsize: 12pt
---

```{r setup, include=FALSE, messages = FALSE, warnings = FALSE}
knitr::opts_chunk$set(echo = FALSE, warnings = FALSE, messages = FALSE)
```

# 1. Introduction

Air pollution is a critical public health concern in urban areas, particularly in London, where long-term exposure to poor air quality contributes to respiratory diseases, cardiovascular issues, and reduced life expectancy. The importance of monitoring and forecasting air quality in London cannot be overstated, as it directly affects public health, the economy, and the overall livability of the city. Timely intervention, such as issuing health advisories, implementing traffic control measures, and enforcing emissions regulations, can help mitigate these risks. By forecasting the Air Quality Index (AQI), stakeholders like the Greater London Authority, UK Environment Agency, Public Health England, Transport for London, and industrial sectors can make informed decisions on pollution control, public health strategies, and urban planning. Additionally, London residents, commuters, and environmental advocacy groups all stand to benefit from better air quality management.

The data used for this project is sourced from Open-Meteo, an open-source weather API that provides free access to weather data for non-commercial use. The dataset contains daily AQI readings for London, using the USAQI (United States Air Quality Index) scale. This scale is commonly employed to assess and report air quality levels, reflecting concentrations of pollutants like particulate matter (PM2.5, PM10), ozone, and nitrogen dioxide. The data spans from January 2, 2013, to February 28, 2025, covering a significant period that captures both long-term trends and seasonal variations in air quality. By leveraging this dataset, the goal of this project is to develop a time series forecasting model to predict future AQI levels, enabling stakeholders to issue early warnings for high pollution days, implement timely pollution control measures, and guide long-term environmental strategies aimed at improving air quality, protecting public health, and promoting sustainable urban development.


# 2. Data 


## 2.1 Data Transformation

## 2.2 Elementary Data Analysis



# 3. Models

## 3.1 ARIMA, SARIMA, ARFIMA 

## 3.2 ETS, Holt Winters

## 3.3 BSTS

## 3.4 LSTM




# 4. Results 




# 5. Discussion


