---
title: "Final_ARIMA_3"
author: "Hritik"
date: "2025-03-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r, include=FALSE}

# Load required libraries
library(tidyverse)
library(lubridate)
library(forecast)
library(tseries)
library(readr)
library(dplyr)
library(ggplot2)
library(lmtest)
library(FinTS)
library(fracdiff)
library(knitr)
library(kableExtra)
library(readxl)

```

```{r}

# Load dataset
#setwd("/Users/hritikjhaveri/Desktop/UChicago/Q2/Time_Series_Analysis_Forcasting/Final_Project")
#getwd()

df <- read_excel("../Data/London_AQI_Daily.xlsx")

# Convert 'Date' column to datetime format
df$Date = as.Date(df$Date, format = "%Y-%m-%d")
df$USAQI = as.integer(df$USAQI)

# View first few rows
head(df)

# Check data types
str(df)

# Check for missing values
sum(is.na(df))

# Summary stats for AQI
summary(df$USAQI)

```

## Data Preparation and Transformations

```{r}

# Ensure ts_data is a daily time series object
train_data <- subset(df, Date < as.Date("2025-1-01"))
test_data  <- subset(df, Date >= as.Date("2025-1-01"))

aqi_train_ts <- ts(train_data$USAQI, frequency = 365, start = c(2013, 1))
aqi_test_ts  <- ts(test_data$USAQI, frequency = 365, start = c(2025, 1))

# Differenced box-cox
boxcox_train <- BoxCox(aqi_train_ts, lambda = (BoxCox.lambda(aqi_train_ts)))

reverse_boxcox <- function(predicted, original, lambda){
  if (lambda == 0){
    exp(predicted)
  }
  else {
    (lambda * predicted + 1)^(1 / lambda)
  }
}

```

## Section 1: ARIMA with No Transformation

```{r}

# ACF and PACF plots for ARIMA with No Transformation
acf(residuals(arima_no_transform), main = "ARIMA(5,1,0) ACF")
pacf(residuals(arima_no_transform), main = "ARIMA(5,1,0) PACF")

# Fit ARIMA model
arima_no_transform <- auto.arima(aqi_train_ts)

# Residuals diagnostics
checkresiduals(arima_no_transform)
plot(fitted(arima_no_transform), residuals(arima_no_transform), 
     main = "ARIMA(5,1,0) Residuals vs. Fit", 
     xlab = "Fitted Values", ylab = "Residuals", col = "blue", pch = 19)
abline(h = 0, col = "red", lwd = 2)

# ADF and KPSS tests
print("Diagnostics for ARIMA(5,1,0)")
print(adf.test(residuals(arima_no_transform)))
print(kpss.test(residuals(arima_no_transform)))

# Forecast
forecast_arima_no_transform <- forecast(arima_no_transform, h = length(aqi_test_ts))

# Calculate RMSE
rmse_arima_no_transform <- sqrt(mean((aqi_test_ts - forecast_arima_no_transform$mean)^2))
print(paste("Test RMSE for ARIMA(5,1,0):", rmse_arima_no_transform))

# Plot forecast with test data
plot(forecast_arima_no_transform, main = "ARIMA(5,1,0) Forecast", xlim = c(2024.8, 2025.2))
lines(aqi_test_ts, col = "red", lwd = 2)
legend("topright", legend = c("Forecast", "Test"), col = c("black", "red"), lty = 1)

# Model summary
print("ARIMA(5,1,0) Summary")
print(summary(arima_no_transform))

```

## Section 2: SARIMA with No Transformation

```{r}

# ACF and PACF plots for SARIMA with No Transformation
acf(residuals(sarima_no_transform), main = "SARIMA(5,1,0) ACF")
pacf(residuals(sarima_no_transform), main = "SARIMA(5,1,0) PACF")

# Fit SARIMA model
sarima_no_transform <- auto.arima(aqi_train_ts, seasonal = TRUE)

# Residuals diagnostics
checkresiduals(sarima_no_transform)
plot(fitted(sarima_no_transform), residuals(sarima_no_transform), 
     main = "SARIMA(5,1,0) Residuals vs. Fit", 
     xlab = "Fitted Values", ylab = "Residuals", col = "blue", pch = 19)
abline(h = 0, col = "red", lwd = 2)

# ADF and KPSS tests
print("Diagnostics for SARIMA(5,1,0)")
print(adf.test(residuals(sarima_no_transform)))
print(kpss.test(residuals(sarima_no_transform)))

# Forecast
forecast_sarima_no_transform <- forecast(sarima_no_transform, h = length(aqi_test_ts))

# Calculate RMSE
rmse_sarima_no_transform <- sqrt(mean((aqi_test_ts - forecast_sarima_no_transform$mean)^2))
print(paste("Test RMSE for SARIMA(5,1,0):", rmse_sarima_no_transform))

# Plot forecast with test data
plot(forecast_sarima_no_transform, main = "SARIMA(5,1,0) Forecast", xlim = c(2024.8, 2025.2))
lines(aqi_test_ts, col = "red", lwd = 2)
legend("topright", legend = c("Forecast", "Test"), col = c("black", "red"), lty = 1)

# Model summary
print("SARIMA(5,1,0) Summary")
print(summary(sarima_no_transform))

```
```{r}
forecast_sarima_no_transform$mean
```

## Section 3: ARFIMA with No Transformation

```{r}

# ACF and PACF plots for ARFIMA with No Transformation
acf(residuals(arfima_no_transform), main = "ARFIMA(0.749, 0.246, -0.253) ACF")
pacf(residuals(arfima_no_transform), main = "ARFIMA(0.749, 0.246, -0.253) PACF")

# Fit ARFIMA model
arfima_no_transform <- arfima(aqi_train_ts)

# Residuals diagnostics
checkresiduals(arfima_no_transform)
plot(fitted(arfima_no_transform), residuals(arfima_no_transform), 
     main = "ARFIMA(0.749, 0.246, -0.253) Residuals vs. Fit", 
     xlab = "Fitted Values", ylab = "Residuals", col = "blue", pch = 19)
abline(h = 0, col = "red", lwd = 2)

# ADF and KPSS tests
print("Diagnostics for ARFIMA")
print(adf.test(residuals(arfima_no_transform)))
print(kpss.test(residuals(arfima_no_transform)))

# Forecast
forecast_arfima_no_transform <- forecast(arfima_no_transform, h = length(aqi_test_ts))

# Calculate RMSE
rmse_arfima_no_transform <- sqrt(mean((aqi_test_ts - forecast_arfima_no_transform$mean)^2))
print(paste("Test RMSE for ARFIMA:", rmse_arfima_no_transform))

# Plot forecast with test data
plot(forecast_arfima_no_transform, main = "ARFIMA(0.749, 0.246, -0.253) Forecast", xlim = c(2024.8, 2025.2))
lines(aqi_test_ts, col = "red", lwd = 2)
legend("topright", legend = c("Forecast", "Test"), col = c("black", "red"), lty = 1)

# Model summary
print("ARFIMA Summary")
print(summary(arfima_no_transform))

```


## Section 4: ARIMA with Box-Cox Transformation

```{r}

# ACF and PACF plots for ARIMA with Box-Cox Transformation
acf(residuals(arima_boxcox), main = "ARIMA(2,1,0) ACF (Box-Cox Transformation)")
pacf(residuals(arima_boxcox), main = "ARIMA(2,1,0) PACF (Box-Cox Transformation)")

# Fit ARIMA model
arima_boxcox <- auto.arima(boxcox_train)

# Residuals diagnostics
checkresiduals(arima_boxcox)
plot(fitted(arima_boxcox), residuals(arima_boxcox), 
     main = "ARIMA(2,1,0) Residuals vs. Fit (Box-Cox Transformation)", 
     xlab = "Fitted Values", ylab = "Residuals", col = "blue", pch = 19)
abline(h = 0, col = "red", lwd = 2)

# ADF and KPSS tests
print("Diagnostics for ARIMA with Box-Cox Transformation")
print(adf.test(residuals(arima_boxcox)))
print(kpss.test(residuals(arima_boxcox)))

# Forecast
forecast_arima_boxcox <- forecast(arima_boxcox, h = length(aqi_test_ts))

# Reverse the Box-Cox transformation
forecast_arima_boxcox_original <- reverse_boxcox(forecast_arima_boxcox$mean, aqi_train_ts, lambda = BoxCox.lambda(aqi_train_ts))

# Calculate RMSE
rmse_arima_boxcox <- sqrt(mean((aqi_test_ts - forecast_arima_boxcox_original)^2))
print(paste("Test RMSE for ARIMA with Box-Cox Transformation:", rmse_arima_boxcox))

#getting last 60 values from train
train_last_60 <- tail(aqi_train_ts, 60)

# Plot forecast with test data (on original scale)
plot(forecast_arima_boxcox_original, main = "ARIMA(2,1,0) Forecast (Box-Cox Transformation)", ylim = c(0, 150 ), xlim = c(2024.85,2025.18), ylab="")
lines(aqi_test_ts, col = "red", lwd = 2)
lines(train_last_60, col = "blue", lwd = 2)
legend("topright", legend = c("Forecast", "Test"), col = c("black", "red"), lty = 1)

# Model summary
print("ARIMA with Box-Cox Transformation Summary")
print(summary(arima_boxcox))

```


## Section 5: SARIMA with Box-Cox Transformation

```{r}

# ACF and PACF plots for SARIMA with Box-Cox Transformation
acf(residuals(sarima_boxcox), main = "SARIMA(2,1,0) ACF (Box-Cox Transformation)")
pacf(residuals(sarima_boxcox), main = "SARIMA(2,1,0) PACF (Box-Cox Transformation)")

# Fit SARIMA model
sarima_boxcox <- auto.arima(boxcox_train, seasonal = TRUE)

# Residuals diagnostics
checkresiduals(sarima_boxcox)
plot(fitted(sarima_boxcox), residuals(sarima_boxcox), 
     main = "SARIMA(2,1,0) Residuals vs. Fit (Box-Cox Transformation)", 
     xlab = "Fitted Values", ylab = "Residuals", col = "blue", pch = 19)
abline(h = 0, col = "red", lwd = 2)

# ADF and KPSS tests
print("Diagnostics for SARIMA with Box-Cox Transformation")
print(adf.test(residuals(sarima_boxcox)))
print(kpss.test(residuals(sarima_boxcox)))

# Forecast
forecast_sarima_boxcox <- forecast(sarima_boxcox, h = length(aqi_test_ts))

# Reverse the Box-Cox transformation
forecast_sarima_boxcox_original <- reverse_boxcox(forecast_sarima_boxcox$mean, aqi_train_ts, lambda = BoxCox.lambda(aqi_train_ts))

# Calculate RMSE
rmse_sarima_boxcox <- sqrt(mean((aqi_test_ts - forecast_sarima_boxcox_original)^2))
print(paste("Test RMSE for SARIMA with Box-Cox Transformation:", rmse_sarima_boxcox))

# Plot forecast with test data (on original scale)
plot(forecast_sarima_boxcox_original, main = "SARIMA(2,1,0) Forecast (Box-Cox Transformation)", ylim = c(0, 150 ), xlim = c(2024.85,2025.18), ylab="")
lines(aqi_test_ts, col = "red", lwd = 2)
lines(train_last_60, col = "blue", lwd = 2)
legend("topright", legend = c("Forecast", "Test"), col = c("black", "red"), lty = 1)

# Model summary
print("SARIMA with Box-Cox Transformation Summary")
print(summary(sarima_boxcox))

```

## Section 6: ARFIMA with Box-Cox Transformation

```{r}

# ACF and PACF plots for ARFIMA with Box-Cox Transformation
acf(residuals(arfima_boxcox), main = "ARFIMA(0.69, 0.18, -0.20) ACF (Box-Cox Transformation)")
pacf(residuals(arfima_boxcox), main = "ARFIMA(0.69, 0.18, -0.20) PACF (Box-Cox Transformation)")

# Fit ARFIMA model
arfima_boxcox <- arfima(boxcox_train)

# Residuals diagnostics
checkresiduals(arfima_boxcox)
plot(fitted(arfima_boxcox), residuals(arfima_boxcox), 
     main = "ARFIMA(0.69, 0.18, -0.20) Residuals vs. Fit (Box-Cox Transformation)", 
     xlab = "Fitted Values", ylab = "Residuals", col = "blue", pch = 19)
abline(h = 0, col = "red", lwd = 2)

# ADF and KPSS tests
print("Diagnostics for ARFIMA with Box-Cox Transformation")
print(adf.test(residuals(arfima_boxcox)))
print(kpss.test(residuals(arfima_boxcox)))

# Forecast
forecast_arfima_boxcox <- forecast(arfima_boxcox, h = length(aqi_test_ts))

# Reverse the Box-Cox transformation
forecast_arfima_boxcox_original <- reverse_boxcox(forecast_arfima_boxcox$mean, aqi_train_ts, lambda = BoxCox.lambda(aqi_train_ts))

# Calculate RMSE
rmse_arfima_boxcox <- sqrt(mean((aqi_test_ts - forecast_arfima_boxcox_original)^2))
print(paste("Test RMSE for ARFIMA with Box-Cox Transformation:", rmse_arfima_boxcox))

# Plot forecast with test data (on original scale)
plot(forecast_arfima_boxcox_original, main = "ARFIMA(0.69, 0.18, -0.20) Forecast (Box-Cox Transformation)", ylim = c(0, 150 ), xlim = c(2024.85,2025.18), ylab="")
lines(aqi_test_ts, col = "red", lwd = 2)
lines(train_last_60, col = "blue", lwd = 2)
legend("topright", legend = c("Forecast", "Test"), col = c("black", "red"), lty = 1)

# Model summary
print("ARFIMA with Box-Cox Transformation Summary")
print(summary(arfima_boxcox))

```
